[package]
name = "git-bfg"
version = "0.3.0"
description = "List largest blob objects in a git repository"
readme = "Readme.md"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
byte-unit = { workspace = true }
clap = { workspace = true }
gix = { workspace = true }
thiserror = { workspace = true }

[[bin]]
name = "bfg"
path = "src/main.rs"
